name: Backup workflow

on:
 workflow_dispatch:
   schedule:
     -cron:'* * * * * '

 jobs:
   Backup:
     runs-on: ubuntu-latest

     steps:
        -name: Checkout code
         uses: actions/checkout@v2

         -name: Set up environments
          run:  |
             chmod +x .github/workflows/github-backup-script.sh
             sudo apt -get -install -y  dowmload dependency

          -name: Run Backup Script
           run: ./.github/workflows/github-backup-script.sh
           env:
            SECRET_KEY:${{ secrets.key }}
